### ISSUE TITLE
JavaScriptコードがひとまとまりになっていることについて

### ISSUE THREAD

**Issue by albatrosary** [html5bizj/x-business-card#1]
JavaScriptが一つにまとまっているが、アクティベートするところは分けるべきでは...

定義したWeb Componentsに
・画像を追加する
・イベントを定義する
といったような内容は
&lt;template&gt;
&lt;script&gt;
SomeThing...
&lt;/script&gt;
&lt;/template&gt;
として定義すべきであるが、アクティベートするロジックは分けるべきではと思います。
また、templateを定義したファイルにアクティベートするロジックを
入れるべきではないと考えます。

如何でしょう？ :-)

**Comment by mitsuruog** [comment]
その通りですね。 :beers: 
アクティベートするコードはComponentの中でやると冗長ですので、まとめて外部ファイル化して、index.htmlで読み込ませるようにします。
それ以外のコードはtemplateの中に含めるようにしますね。

**Comment by mitsuruog** [comment]
`work`ブランチ作って修正中です。

**Comment by mitsuruog** [comment]
workブランチに修正したもの上げました。

アクティベートの外部化についてですが、アクティベートとCustomElement登録タイミングの関連で悩んだので、一旦保留にしています。
（ハンズオンでは一旦これで十分だと思います。）

`registerElement`と`アクティベート`を同じタイミングでやらないと、registerElement時に発火するcreatedCallback内の処理にてshadowDOMが無い状態でエラーになってしまいます。
また、registerElementする際に、CustomElementのprototypeを設定するのですが、そこまで外部化してしまうと、あまりcomponentっぽくないので一旦保留にしています。

**Comment by mitsuruog** [comment]
一旦クローズ
